baseurl = "http://hobotest.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Hobo Test"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = ""
#googleAnalytics = ""

[permalinks]
  post = "/:year/:month/:day/:title/"

[Params]
  subtitle = "Testin' my way down the information superhighway..."
  logo = "img/cropped-networkhobo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  #gcse = "" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  [Params.staticman]
  api = "https://api.staticman.net/v2/entry/dancwilliams/hobotest/master/comments"
  pulls = "https://github.com/dancwilliams/hobotest/pulls"
  [Params.staticman.recaptcha]
    sitekey = "6Le5eCgUAAAAAI3x5sDCrbtIJcYbQ4S5y1tCMCuG"
    secret = "pZxw/5TAF0lRc6VfpihA8vol/xrlZC4O8wRY4p9PG+EWcbnY8SUyu30WuKoh+d8tAexKki97io6khS/JkXTRaL8Udo2zIKMKfmdAMK7VwVXZrPyv65vKeqRQpHbamHr4Mpg5cKSlaE3wOTgm9pw6/MM+EfyxKv6qp2R6kNK4vNE=""

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Dan C Williams"
  email = "dan@networkhobo.com"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "dancwilliams"
  twitter = "dancwilliams"
#  reddit = "username"
  linkedin = "danielcwilliams"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
  youtube = "channel/UCHuOvIJOUujSGpt021fYxww" # or user/dancwilliams
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 2

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 4

#[[menu.main]]
#    name = "Roadmap"
#    url = "roadmap"
#    weight = 5